version: "3.9"

services:

  mysql:
    image: mysql:5.7
    volumes:
      - mysql:/var/lib/mysql
    networks:
      back:
        aliases:
          - mysql
    environment:
      MYSQL_DATABASE: blog
      MYSQL_USER: bloguser
      MYSQL_PASSWORD: blogpass
      MYSQL_RANDOM_ROOT_PASSWORD: 1

  back:
    build: back/
    networks:
      - back
    volumes:
      - maven-repo:/root/.m2
    ports:
      - "8080:8080"
    environment:
      HTTP_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/blog
      SPRING_DATASOURCE_USERNAME: bloguser
      SPRING_DATASOURCE_PASSWORD: blogpass
      JWT_SECRET: test

  front:
    build:
      context: front/
      args:
        REACT_APP_HOST: localhost:8080
    ports:
      - "3000:80"

networks:
  back:

volumes:
  maven-repo:
  mysql:
